### ISSUE TITLE
bootstrap-theme.css not required

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-karan/Bootstrap#49]
where do u need this ?

**Comment by mekaransethi** [comment]
bootstrap-theme.css  now removed 
<head>
<meta charset="UTF-8">
<title>Welcome to Teckgeeks</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='http://fonts.googleapis.com/css?family=Acme' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Amita' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Aclonica' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="css/plugins/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="css/plugins/bootstrap/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/custom/style.css">
</head>
