### ISSUE TITLE
bootstrap.css minified file to be used

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-karan/Bootstrap#50]
bootstrap.css should be replaced with bootstrap.min.css

minified files load more faster and are less in size.

**Comment by mekaransethi** [comment]
Resolve using minified file
<head>
<meta charset="UTF-8">
<title>Welcome to Teckgeeks</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='http://fonts.googleapis.com/css?family=Acme' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Amita' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Aclonica' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="css/plugins/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="css/plugins/bootstrap/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="css/custom/style.css">
</head>
