### ISSUE TITLE
Menu and site content overlapping

### ISSUE THREAD

**Issue by ibigrock-ashish** [ibigrock-karan/Bootstrap#51]
![screenshot from 2017-07-04 03-26-29](https://user-images.githubusercontent.com/28713151/27808898-bbf80cce-6068-11e7-8906-d9ae278a488e.png)

**Comment by mekaransethi** [comment]
![image](https://user-images.githubusercontent.com/28711948/27877443-3e4a5b80-61d8-11e7-9ef1-cd0ba5bfeb2c.png)
this issue is resolved
