### ISSUE TITLE
All 3 social links redirecting to top of site when mouse clicked.

### ISSUE THREAD

**Issue by ibigrock-ashish** [ibigrock-karan/Bootstrap#52]

**Comment by mekaransethi** [comment]
<Footer>
<p>
<h6>Copyright &copy; Karan Sethi
   <a #="#" class="fa fa-facebook"></a>
   <a #="#" class="fa fa-twitter"></a>
   <a #="#" class="fa fa-google"></a>
</h6></p>
</Footer>
