### ISSUE TITLE
use in built classes of bootstrap

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-karan/Bootstrap#54]
```
<nav class="col-md-10 shift"> // class - shift // what is this class for ? why cant u use bult-in classes of bootstrap for this ?
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Downloads</a></li>
      <li><a href="#">More</a></li>
      <li><a href="#">Nice staff</a></li>
    </ul>
  </nav>
```

**Comment by mekaransethi** [comment]
<nav class="navbar navbar-light bg-faded navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
  <a class="navbar-brand" href="#">
    <img src="image/logo.png" width="200" height="50" class="d-inline-block align-top" alt="logo"> 
  </a>
  </div>
    <ul class="nav navbar-nav">
       <li><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Downloads</a></li>
      <li><a href="#">More</a></li>
      <li><a href="#">Nice staff</a></li>
    </ul>
  </div>
</nav>
