### ISSUE TITLE
missing end tags in index.html

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-karan/Bootstrap#55]
index.html
```
<Footer>
<p> // where is the end tag for <p> ???
<h6>Copyright &copy; Karan Sethi
   <a href="#" class="fa fa-facebook"></a>
   <a href="#" class="fa fa-twitter"></a>
   <a href="#" class="fa fa-google"></a>
</h6>
</Footer>
```

**Comment by ibigrock-karan** [comment]
<Footer>
<p>
<h6>Copyright &copy; Karan Sethi
   <a href="#" class="fa fa-facebook"></a>
   <a href="#" class="fa fa-twitter"></a>
   <a href="#" class="fa fa-google"></a>
</h6></p>
</Footer>

**Comment by ibigrock-karan** [comment]
index.html

<Footer>
<p>
<h6>Copyright &copy; Karan Sethi
   <a #="fb.com" class="fa fa-facebook"></a>
   <a #="twitter.com" class="fa fa-twitter"></a>
   <a #="pluse,google.com" class="fa fa-google"></a>
</h6></p>
</Footer>

**Comment by ibigrock-karan** [comment]
<Footer>
<p>
<h6>Copyright &copy; Karan Sethi
   <a #="fb.com" class="fa fa-facebook"></a>
   <a #="twitter.com" class="fa fa-twitter"></a>
   <a #="pluse,google.com" class="fa fa-google"></a>
</h6></p>
</Footer>

**Comment by mekaransethi** [comment]
<Footer>
<p>
<h6>Copyright &copy; Karan Sethi
   <a #="fb.com" class="fa fa-facebook"></a>
   <a #="twitter.com" class="fa fa-twitter"></a>
   <a #="pluse,google.com" class="fa fa-google"></a>
</h6></p>
</Footer>
