### ISSUE TITLE
make all your image file name in small letter

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-karan/Bootstrap#65]
![image](https://user-images.githubusercontent.com/27997683/28191217-b5c5fb36-684c-11e7-9467-2675915f228d.png)

**Comment by ms-tech-geek** [comment]
why issues 40 - 48 were closed without solving ?

**Comment by ms-tech-geek** [comment]
https://github.com/ibigrock-karan/Bootstrap/issues/40
https://github.com/ibigrock-karan/Bootstrap/issues/41
https://github.com/ibigrock-karan/Bootstrap/issues/42
https://github.com/ibigrock-karan/Bootstrap/issues/43
https://github.com/ibigrock-karan/Bootstrap/issues/44
https://github.com/ibigrock-karan/Bootstrap/issues/45
https://github.com/ibigrock-karan/Bootstrap/issues/46
https://github.com/ibigrock-karan/Bootstrap/issues/47
https://github.com/ibigrock-karan/Bootstrap/issues/48

**Comment by mekaransethi** [comment]
resolved
